# Generated by Django 5.2.7 on 2025-12-15 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('for_whom', models.CharField(choices=[('self', 'Self'), ('dependant', 'Dependant')], default='self', max_length=20)),
                ('status', models.CharField(choices=[('in_process', 'In Process'), ('active', 'Active'), ('archived', 'Archived')], default='in_process', max_length=20)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('mood_today', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Okay'), (4, 'Good'), (5, 'Very Good')], null=True)),
                ('height_unit', models.CharField(blank=True, choices=[('feet', 'Feet & Inches'), ('cm', 'Centimeters')], max_length=10, null=True)),
                ('height_feet', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_inches', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.CharField(blank=True, choices=[('underweight', 'Underweight'), ('normal', 'Normal'), ('overweight', 'Overweight'), ('obese', 'Obese')], max_length=20, null=True)),
                ('health_opinion', models.CharField(blank=True, max_length=20, null=True)),
                ('presenting_illness', models.CharField(blank=True, choices=[('cough', 'Cough'), ('cold', 'Cold'), ('fever', 'Fever'), ('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('asthma', 'Asthma'), ('fine', 'I am fine'), ('other', 'Other')], max_length=50, null=True)),
                ('presenting_illness_other', models.CharField(blank=True, max_length=255, null=True)),
                ('chronic_illness', models.BooleanField(blank=True, null=True)),
                ('chronic_illness_details', models.CharField(blank=True, max_length=255, null=True)),
                ('surgery_history', models.BooleanField(blank=True, null=True)),
                ('surgery_history_details', models.CharField(blank=True, max_length=255, null=True)),
                ('sleep_hours', models.CharField(blank=True, choices=[('lt_7', 'Less than 7 hours'), ('gt_7', 'More than 7 hours')], max_length=10, null=True)),
                ('wakeup_midnight', models.BooleanField(blank=True, null=True)),
                ('wakeup_midnight_reasons', models.CharField(blank=True, choices=[('excessive_urination', 'Excessive Urination'), ('breathing_difficulty', 'Breathing Difficulty'), ('stress', 'Stress'), ('body_over_heat', 'Body Over Heat'), ('indigestion', 'Indigestion'), ('anxiety_depression', 'Anxiety / Depression')], max_length=255, null=True)),
                ('tired_morning', models.BooleanField(blank=True, null=True)),
                ('junk_food_freq', models.CharField(blank=True, choices=[('never', 'Never or almost never'), ('occasionally', 'Occasionally'), ('often', 'Often'), ('very_often', 'Very often'), ('always', 'Always or almost always')], max_length=20, null=True)),
                ('fruits_veg_freq', models.CharField(blank=True, choices=[('never', 'Never or almost never'), ('occasionally', 'Occasionally'), ('often', 'Often'), ('very_often', 'Very often'), ('always', 'Always or almost always')], max_length=20, null=True)),
                ('milk_dairy_freq', models.CharField(blank=True, choices=[('never', 'Never or almost never'), ('occasionally', 'Occasionally'), ('often', 'Often'), ('very_often', 'Very often'), ('always', 'Always or almost always')], max_length=20, null=True)),
                ('water_intake', models.CharField(blank=True, choices=[('lt_9', 'Less than 9 glasses'), ('gt_9', 'More than 9 glasses')], max_length=10, null=True)),
                ('is_veg', models.BooleanField(default=True)),
                ('non_veg_freq', models.CharField(blank=True, choices=[('never', 'Never or almost never'), ('occasionally', 'Occasionally'), ('often', 'Often'), ('very_often', 'Very often'), ('always', 'Always or almost always')], max_length=20, null=True)),
                ('alcohol_current', models.BooleanField(blank=True, null=True)),
                ('alcohol_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly once'), ('occasional', 'Occasional drinker')], max_length=20, null=True)),
                ('alcohol_quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('alcohol_duration', models.CharField(blank=True, choices=[('lt_1', '<1yr'), ('1_5', '1–5yrs'), ('5_10', '5–10yrs'), ('gt_10', '>10yrs')], max_length=20, null=True)),
                ('alcohol_planning_quit', models.BooleanField(blank=True, null=True)),
                ('alcohol_past', models.BooleanField(blank=True, null=True)),
                ('alcohol_quit_period', models.CharField(blank=True, choices=[('lt_1', '<1yr'), ('1_3', '1–3yrs'), ('3_5', '3–5yrs'), ('gt_5', '>5yrs')], max_length=20, null=True)),
                ('tobacco_current', models.BooleanField(blank=True, null=True)),
                ('tobacco_type', models.CharField(blank=True, choices=[('cigarette', 'Cigarette'), ('bedi', 'Bedi'), ('gutka', 'Gutka'), ('raw_tobacco', 'Raw Tobacco'), ('pan', 'Pan')], max_length=20, null=True)),
                ('tobacco_duration', models.CharField(blank=True, choices=[('lt_1', '<1yr'), ('1_5', '1–5yrs'), ('5_10', '5–10yrs'), ('gt_10', '>10yrs')], max_length=20, null=True)),
                ('tobacco_planning_quit', models.BooleanField(blank=True, null=True)),
                ('tobacco_quit', models.BooleanField(blank=True, null=True)),
                ('tobacco_quit_period', models.CharField(blank=True, choices=[('lt_1', '<1yr'), ('1_3', '1–3yrs'), ('3_5', '3–5yrs'), ('gt_5', '>5yrs')], max_length=20, null=True)),
                ('family_chronic_illness', models.BooleanField(blank=True, null=True)),
                ('checkup_frequency', models.CharField(blank=True, choices=[('six_months', 'Every six months'), ('yearly', 'Yearly once'), ('few_times', 'Few times in life')], max_length=20, null=True)),
                ('taking_regular_meds', models.BooleanField(blank=True, null=True)),
                ('stopped_meds_without_doctor', models.BooleanField(blank=True, null=True)),
                ('other_alt_medicine', models.BooleanField(blank=True, null=True)),
                ('difficulty_urine', models.BooleanField(blank=True, null=True)),
                ('difficulty_urine_reasons', models.CharField(blank=True, choices=[('flow_difficulty', 'Difficulty in flow of urine'), ('blood_urination', 'Blood tinged urination'), ('pain_while_urinating', 'Pain while urinating')], max_length=255, null=True)),
                ('difficulty_stools', models.BooleanField(blank=True, null=True)),
                ('stretch_duration', models.CharField(blank=True, choices=[('lt_30', 'Less than 30 mins'), ('30_60', '30 mins - 1 hr'), ('gt_60', 'More than 1 hr'), ('none', 'Not really')], max_length=10, null=True)),
                ('cardio_duration', models.CharField(blank=True, choices=[('lt_30', 'Less than 30 mins'), ('30_60', '30 mins - 1 hr'), ('gt_60', 'More than 1 hr'), ('none', 'Not really')], max_length=10, null=True)),
                ('strength_duration', models.CharField(blank=True, choices=[('lt_30', 'Less than 30 mins'), ('30_60', '30 mins - 1 hr'), ('gt_60', 'More than 1 hr'), ('none', 'Not really')], max_length=10, null=True)),
                ('walking_duration', models.CharField(blank=True, choices=[('lt_30', 'Less than 30 mins'), ('30_60', '30 mins - 1 hr'), ('gt_60', 'More than 1 hr'), ('none', 'Not really')], max_length=10, null=True)),
                ('other_activity', models.CharField(blank=True, choices=[('none', 'None'), ('running', 'Running'), ('sports', 'Playing any sport'), ('cycling', 'Cycling'), ('gymnastics', 'Gymnastics'), ('other', 'Other')], max_length=20, null=True)),
                ('low_interest', models.BooleanField(blank=True, null=True)),
                ('depressed', models.BooleanField(blank=True, null=True)),
                ('sleep_appetite_issue', models.BooleanField(blank=True, null=True)),
                ('low_energy', models.BooleanField(blank=True, null=True)),
                ('anxious', models.BooleanField(blank=True, null=True)),
                ('work_stress_affecting_life', models.BooleanField(blank=True, null=True)),
                ('work_stress_reasons', models.CharField(blank=True, choices=[('increased_workload', 'Increased Workload'), ('long_working_hours', 'Long Working Hours'), ('health_issues', 'Any Health Issues'), ('financial_issue', 'Financial Issue'), ('others', 'Others')], max_length=255, null=True)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('risk_category', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='health_assessments/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('dependant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_assessments', to='dependants.dependant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FamilyIllnessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(choices=[('heart_disease', 'Heart Disease'), ('stroke', 'Stroke'), ('hypertension', 'Hypertension'), ('cancer', 'Cancer'), ('depression', 'Depression'), ('type2_diabetes', 'Type 2 Diabetes'), ('arthritis', 'Arthritis'), ('osteoporosis', 'Osteoporosis'), ('asthma', 'Asthma'), ('copd', 'Chronic Obstructive Pulmonary Disease (COPD)'), ('kidney_disease', 'Chronic Kidney Disease'), ('oral_disease', 'Oral Disease')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_history', to='dependants.dependant')),
                ('hra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_illness_records', to='health_assessment.healthassessment')),
            ],
        ),
    ]
