# Generated by Django 5.2.7 on 2025-12-15 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('business_line', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gym_service/logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GymPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration_months', models.PositiveSmallIntegerField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('features', models.CharField(default=list, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_logo', models.ImageField(blank=True, null=True, upload_to='gym_service/packages/vendor_logo')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('booking_for', models.CharField(choices=[('self', 'Self'), ('dependant', 'Dependant')], default='self', max_length=16)),
                ('contact_number', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=1024, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('dependant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dependants.dependant')),
                ('gym_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym_service.gymcenter')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym_service.gympackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
