# Generated by Django 5.2.7 on 2025-12-15 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('medicine_name', models.CharField(max_length=255)),
                ('medicine_type', models.CharField(choices=[('syrup', 'Syrup'), ('tablet', 'Tablet'), ('drops', 'Drops'), ('inhalers', 'Inhalers'), ('injections', 'Injections'), ('cream_gel', 'Cream/Gel')], max_length=20)),
                ('duration_value', models.PositiveIntegerField(default=1)),
                ('duration_unit', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='day', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('frequency_type', models.CharField(choices=[('fixed_times', 'Fixed Times'), ('interval', 'Interval')], max_length=20)),
                ('intake_frequency', models.CharField(blank=True, choices=[('once', 'Once'), ('twice', 'Twice'), ('thrice', 'Thrice'), ('four_times', 'Four times'), ('unknown', 'Unknown')], max_length=20, null=True)),
                ('interval_type', models.CharField(blank=True, choices=[('every_30_minutes', 'Every 30 minutes'), ('hourly', 'Hourly'), ('every_4_hours', 'Every 4 hours')], max_length=30, null=True)),
                ('interval_start_time', models.TimeField(blank=True, null=True)),
                ('interval_end_time', models.TimeField(blank=True, null=True)),
                ('dosage_value', models.PositiveIntegerField(default=1)),
                ('dosage_unit', models.CharField(choices=[('tablespoons', 'Tablespoons'), ('tablet', 'Tablet'), ('drops', 'Drops'), ('as_directed', 'As directed by physician')], max_length=20)),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment_reminder_date', models.DateField(blank=True, null=True)),
                ('current_inventory', models.PositiveIntegerField(default=0)),
                ('remind_when_inventory', models.PositiveIntegerField(default=0)),
                ('medicines_left', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicineReminderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='medicine_reminders/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='medicine_reminders.medicinereminder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicineReminderTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('meal_relation', models.CharField(choices=[('before_meal', 'Before meal'), ('after_meal', 'After meal'), ('with_meal', 'With meal'), ('none', 'No relation')], default='none', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_times', to='medicine_reminders.medicinereminder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
