# Generated by Django 5.2.7 on 2025-12-26 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('systolic', models.PositiveIntegerField(help_text='Systolic pressure (upper value)')),
                ('diastolic', models.PositiveIntegerField(help_text='Diastolic pressure (lower value)')),
                ('unit', models.CharField(choices=[('mmHg', 'MMHG')], default='mmHg', max_length=10)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('exercise', 'Exercise'), ('rest', 'Rest'), ('other', 'Other')], default='normal', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_pressure_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blood Pressure Record',
                'verbose_name_plural': 'Blood Pressure Records',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BmiRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.FloatField(help_text='Body Mass Index value')),
                ('unit', models.CharField(choices=[('BMI', 'Body Mass Index'), ('kg/m²', 'Kilograms per square meter')], default='kg/m²', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmi_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BMI Record',
                'verbose_name_plural': 'BMI Records',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GlucoseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.FloatField(help_text='Blood glucose value')),
                ('unit', models.CharField(choices=[('mg/dL', 'Milligrams per Deciliter'), ('mmol/l', 'Millimoles per Liter')], default='mg/dl', max_length=10)),
                ('test_type', models.CharField(choices=[('fasting', 'Fasting'), ('postprandial', 'Postprandial (After Meal)'), ('random', 'Random')], default='fasting', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glucose_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Glucose Record',
                'verbose_name_plural': 'Glucose Records',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HeartRateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('bpm', 'Beats Per Minute')], default='bpm', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_rate_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Heart Rate Record',
                'verbose_name_plural': 'Heart Rate Records',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('unit', models.CharField(choices=[('cm', 'Centimeters'), ('ft', 'Feet')], default='cm', max_length=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='height_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Height Record',
                'verbose_name_plural': 'Height Records',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OxygenSaturationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.FloatField(help_text='Oxygen saturation percentage')),
                ('unit', models.CharField(choices=[('%', 'Percentage')], default='%', max_length=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxygen_saturation_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oxygen Saturation Record',
                'verbose_name_plural': 'Oxygen Saturation Records',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', max_length=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weight Record',
                'verbose_name_plural': 'Weight Records',
                'ordering': ['-updated_at'],
            },
        ),
    ]
