# Generated by Django 5.2.7 on 2025-12-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressurerecord',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodpressurerecord',
            name='unit',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bmirecord',
            name='unit',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='test_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='glucoserecord',
            name='unit',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='heartraterecord',
            name='unit',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='heightrecord',
            name='unit',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='oxygensaturationrecord',
            name='unit',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='unit',
            field=models.CharField(max_length=5),
        ),
    ]
