# Generated by Django 5.2.7 on 2025-12-15 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation_filter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('detailed_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dental_treatments/')),
            ],
        ),
        migrations.CreateModel(
            name='EyeTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('detailed_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='eye_treatments/')),
            ],
        ),
        migrations.CreateModel(
            name='DentalVendorAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_addresses', to='consultation_filter.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='EyeVendorAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_addresses', to='consultation_filter.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='EyeDentalVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('booking_for', models.CharField(choices=[('self', 'Self'), ('dependant', 'Dependant')], default='self', max_length=20)),
                ('dependant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dependant_relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('service_type', models.CharField(choices=[('eye', 'Eye Care'), ('dental', 'Dental Care')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dental_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eyedental_care.dentaltreatment')),
                ('dental_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eyedental_care.dentalvendoraddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('eye_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eyedental_care.eyetreatment')),
                ('eye_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eyedental_care.eyevendoraddress')),
            ],
        ),
    ]
