# Generated by Django 4.2.25 on 2025-12-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofessionaldetails',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
