# Generated by Django 5.2.7 on 2025-12-15 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dependants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('policy_owner_type', models.CharField(choices=[('company', 'Company Policy'), ('self', 'Self'), ('dependant', 'Dependent')], default='self', max_length=20)),
                ('for_whom', models.CharField(choices=[('self', 'Self'), ('dependant', 'Dependant')], default='self', max_length=20)),
                ('plan_type', models.CharField(choices=[('individual', 'Individual'), ('floater', 'Floater')], default='individual', max_length=20)),
                ('is_self_included', models.BooleanField(default=True)),
                ('policy_holder_name', models.CharField(max_length=255)),
                ('policy_from', models.DateField()),
                ('policy_to', models.DateField()),
                ('type_of_insurance', models.CharField(choices=[('health', 'Health Insurance'), ('life', 'Life Insurance'), ('personal_accident', 'Personal Accident'), ('critical_illness', 'Critical Illness'), ('other', 'Other')], max_length=50)),
                ('insurance_company', models.CharField(max_length=255)),
                ('policy_number', models.CharField(max_length=100)),
                ('policy_name', models.CharField(max_length=255)),
                ('sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tpa', models.CharField(blank=True, max_length=255, null=True)),
                ('nominee', models.CharField(blank=True, max_length=255, null=True)),
                ('renewal_reminder_enabled', models.BooleanField(default=False)),
                ('renewal_frequency', models.CharField(blank=True, choices=[('one_time', 'One time'), ('recurring', 'Recurring')], max_length=20, null=True)),
                ('renewal_reminder_type', models.CharField(blank=True, choices=[('days', 'Days'), ('two_weeks', '2 Week'), ('one_week', '1 Week'), ('one_month', '1 Month')], max_length=20, null=True)),
                ('renewal_reminder_value', models.PositiveIntegerField(default=1, help_text='Number of days/weeks/months before policy_to date.')),
                ('group_policy_details', models.TextField(blank=True, null=True)),
                ('policy_features', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('dependant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_insurance_policies', to='dependants.dependant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='insurance_records/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='insurance_records.insurancepolicyrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceFloaterMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_self', models.BooleanField(default=False)),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('dependant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floater_entries', to='dependants.dependant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floater_members', to='insurance_records.insurancepolicyrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
