# Generated by Django 5.2.7 on 2025-12-15 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WomanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CycleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_period_length', models.PositiveSmallIntegerField(help_text='Days of bleeding (e.g. 4)')),
                ('avg_cycle_length', models.PositiveSmallIntegerField(help_text='Days between starts of periods (e.g. 28)')),
                ('last_period_start', models.DateField(help_text='YYYY-MM-DD - first day of last period')),
                ('next_period_start', models.DateField(blank=True, null=True)),
                ('next_period_end', models.DateField(blank=True, null=True)),
                ('ovulation_date', models.DateField(blank=True, null=True)),
                ('fertile_window_start', models.DateField(blank=True, null=True)),
                ('fertile_window_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.ManyToManyField(blank=True, related_name='cycle_entries', to='women_health.symptoms')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='women_health.womanprofile')),
            ],
        ),
    ]
