# Generated by Django 5.2.7 on 2025-12-15 09:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_packages', '0001_initial'),
        ('labfilter', '0001_initial'),
        ('labtest', '0001_initial'),
        ('location', '0001_initial'),
        ('sponsored_packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('active', models.BooleanField(default=True)),
                ('work_start', models.TimeField(default=datetime.time(8, 0))),
                ('work_end', models.TimeField(default=datetime.time(20, 0))),
                ('slot_interval_minutes', models.IntegerField(default=30)),
                ('slot_capacity', models.IntegerField(default=1)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_centers', to='location.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('health_packages', models.ManyToManyField(blank=True, related_name='diagnostic_centers', to='health_packages.healthpackage')),
                ('sponsored_packages', models.ManyToManyField(blank=True, related_name='diagnostic_centers', to='sponsored_packages.sponsoredpackage')),
                ('tests', models.ManyToManyField(related_name='diagnostic_centers', to='labtest.test')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('visit_types', models.ManyToManyField(blank=True, related_name='diagnostic_centers', to='labfilter.visittype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
